name: kokorahenn_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  flutter:
    sdk: flutter
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  import_sorter: ^4.6.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1

dev_dependencies:
flutter_lints: ^2.0.0
flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
