name: kokorahenn_flutter
description: "Facility Search Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  envied: ^0.5.3
  flutter:
    sdk: flutter
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  retrofit: ^4.1.0
  settings_ui: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.11
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1

  retrofit_generator: ^8.1.0
  
flutter_test:
  sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"


flutter_native_splash:
  color: '#f19a38'
  image: 'assets/images/splash_icon.png'
  color_dark: '#f19a38'
  image_dark: 'assets/images/splash_icon.png'
  fullscreen: true
  android_12:
    icon_background_color: '#f19a38'
    image: 'assets/images/splash_icon.png'
    icon_background_color_dark: '#f19a38'
    image_dark: 'assets/images/splash_icon.png'